server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/esport
    username: postgres
    password: postgres

  sql:
    init:
      mode: always
      schema-locations: classpath:users_table.sql

  jpa:
    hibernate:
      ddl-auto: none  # disables automatic table creation/modification
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
